# Generated by Django 4.2 on 2023-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userpreferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="currency",
            field=models.CharField(
                blank=True, default="USD", max_length=255, null=True
            ),
        ),
    ]
